[package]
name = "gthttp"
version = "0.1.0"
authors = ["Jordan Hand <jordanhand22@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
pnet = "0.22"
ctrlc = "3.1.1"
tiny_http = "0.6.2"
error-chain = "0.11"

