[package]
name = "shijackr"
version = "0.1.0"
authors = ["Jordan Hand <jordanhand22@gmail.com", "kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
readme = "README.md"

[dependencies]
clap = "2"
pnet = "0.21"
env_logger = "0.5"
log = "0.4"
error-chain = "0.11"
pktparse = "0.2"
nom = "3"
